const tripSelect=document.querySelector("#splitzTripSelect");
const accessNote=document.querySelector("#splitzAccessNote");
const splitzEmpty=document.querySelector("#splitzEmpty");
const splitzWorkspace=document.querySelector("#splitzWorkspace");
const personForm=document.querySelector("#splitzPersonForm");
const personName=document.querySelector("#splitzPersonName");
const peopleEl=document.querySelector("#splitzPeople");
const expenseForm=document.querySelector("#splitzExpenseForm");
const expenseTitle=document.querySelector("#splitzExpenseTitle");
const expenseAmount=document.querySelector("#splitzExpenseAmount");
const paidBy=document.querySelector("#splitzPaidBy");
const balancesEl=document.querySelector("#splitzBalances");
const settlementsEl=document.querySelector("#splitzSettlements");
const expensesEl=document.querySelector("#splitzExpenses");

let trips=[],activeTrip=null,members=[],finances={people:[],expenses:[]};

async function api(path,options={}){const res=await fetch(path,{credentials:"same-origin",headers:{"content-type":"application/json",...(options.headers||{})},...options});let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data.error||"Something went wrong.");return data}
function esc(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML}
function money(v){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v)||0)}
function canEdit(){return activeTrip && activeTrip.access!=="shared"}
function calc(){const b=Object.fromEntries(finances.people.map(p=>[p.id,0]));finances.expenses.forEach(e=>{if(!finances.people.length)return;const share=Number(e.amount)/finances.people.length;finances.people.forEach(p=>b[p.id]=(b[p.id]||0)-share);b[e.paidBy]=(b[e.paidBy]||0)+Number(e.amount)});const cs=Object.entries(b).filter(([,v])=>v>.005).map(([id,v])=>({id,amount:v})).sort((a,b)=>b.amount-a.amount),ds=Object.entries(b).filter(([,v])=>v<-.005).map(([id,v])=>({id,amount:-v})).sort((a,b)=>b.amount-a.amount),s=[];let c=0,d=0;while(c<cs.length&&d<ds.length){const a=Math.min(cs[c].amount,ds[d].amount);if(a>.005)s.push({from:ds[d].id,to:cs[c].id,amount:a});cs[c].amount-=a;ds[d].amount-=a;if(cs[c].amount<.005)c++;if(ds[d].amount<.005)d++}return{balances:b,settlements:s}}
async function save(){if(!canEdit())return;await api("/api/splitz",{method:"PUT",body:JSON.stringify({tripId:activeTrip.id,finances})})}
async function loadTrips(){try{const me=await api("/api/auth/me");if(!me.user){showMessage("Log in to use shared Splitz finances.");return}const data=await api("/api/trips");trips=data.trips||[];tripSelect.innerHTML=trips.length?trips.map(t=>'<option value="'+t.id+'">'+esc(t.title)+'</option>').join(""):'<option value="">No itineraries yet</option>';tripSelect.disabled=!trips.length;if(!trips.length){showMessage("Create an itinerary first, then return to Splitz.");return}await loadTrip(trips[0].id)}catch(e){showMessage(e.message)}}
function showMessage(msg){splitzWorkspace.hidden=true;splitzEmpty.hidden=false;splitzEmpty.querySelector("p").textContent=msg}
async function loadTrip(id){activeTrip=trips.find(t=>String(t.id)===String(id))||null;if(!activeTrip)return;const data=await api("/api/splitz?tripId="+encodeURIComponent(activeTrip.id),{method:"GET",headers:{}});members=data.members||[];finances=data.finances||{people:[],expenses:[]};finances.people=Array.isArray(finances.people)?finances.people:[];finances.expenses=Array.isArray(finances.expenses)?finances.expenses:[];if(!finances.people.length&&members.length&&canEdit()){finances.people=members.map(m=>({id:m.id,name:m.name||m.email}));await save()}render()}
function render(){splitzEmpty.hidden=true;splitzWorkspace.hidden=false;const editable=canEdit();accessNote.textContent=activeTrip.access==="owner"?"You own this itinerary · Full edit access":activeTrip.access==="editor"?"Shared with you · You can edit itinerary & Splitz":"Shared with you · View only";personForm.hidden=!editable;expenseForm.hidden=!editable;peopleEl.innerHTML=finances.people.length?finances.people.map(p=>'<span class="splitz-person-chip">'+esc(p.name)+(editable?'<button type="button" data-person="'+p.id+'">×</button>':'')+'</span>').join(""):'<p class="splitz-muted">No people added yet.</p>';paidBy.innerHTML=finances.people.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join("");const r=calc(),name=id=>finances.people.find(p=>p.id===id)?.name||"Friend";balancesEl.innerHTML=finances.people.length?finances.people.map(p=>{const a=r.balances[p.id]||0,st=a>.005?"gets back":a<-.005?"owes":"is settled";return '<div class="splitz-balance-row"><strong>'+esc(p.name)+'</strong><span class="'+(a>.005?'positive':a<-.005?'negative':'')+'">'+st+(Math.abs(a)>.005?' '+money(Math.abs(a)):'')+'</span></div>'}).join(""):'<p class="splitz-muted">No balances yet.</p>';settlementsEl.innerHTML=r.settlements.length?'<div class="splitz-settlement-title">Suggested payments</div>'+r.settlements.map(x=>'<div class="splitz-settlement"><strong>'+esc(name(x.from))+'</strong><span>pays</span><strong>'+esc(name(x.to))+'</strong><b>'+money(x.amount)+'</b></div>').join(""):(finances.expenses.length?'<div class="splitz-all-set">✓ Everyone is settled up</div>':'');expensesEl.innerHTML=finances.expenses.length?finances.expenses.slice().reverse().map(e=>'<div class="splitz-expense-row"><div><strong>'+esc(e.title)+'</strong><small>Paid by '+esc(name(e.paidBy))+'</small></div><span>'+money(e.amount)+'</span>'+(editable?'<button type="button" data-expense="'+e.id+'">×</button>':'')+'</div>').join(""):'<p class="splitz-muted">No expenses yet.</p>';if(editable){peopleEl.querySelectorAll("[data-person]").forEach(btn=>btn.onclick=async()=>{if(finances.expenses.some(e=>e.paidBy===btn.dataset.person)){alert("Delete this person's expenses first.");return}finances.people=finances.people.filter(p=>p.id!==btn.dataset.person);await save();render()});expensesEl.querySelectorAll("[data-expense]").forEach(btn=>btn.onclick=async()=>{finances.expenses=finances.expenses.filter(e=>e.id!==btn.dataset.expense);await save();render()})}}
tripSelect.addEventListener("change",e=>loadTrip(e.target.value));
personForm.addEventListener("submit",async e=>{e.preventDefault();if(!canEdit())return;const n=personName.value.trim();if(!n)return;if(finances.people.some(p=>p.name.toLowerCase()===n.toLowerCase())){alert("That person is already included.");return}finances.people.push({id:crypto.randomUUID(),name:n});e.target.reset();await save();render()});
expenseForm.addEventListener("submit",async e=>{e.preventDefault();if(!canEdit())return;if(finances.people.length<2){alert("Add at least two people before adding an expense.");return}const title=expenseTitle.value.trim(),amount=Number(expenseAmount.value),payer=paidBy.value;if(!title||!payer||!Number.isFinite(amount)||amount<=0)return;finances.expenses.push({id:crypto.randomUUID(),title,amount,paidBy:payer,createdAt:Date.now()});e.target.reset();await save();render()});
loadTrips();